routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Auth::routes();

Route::resource('profile', 'ProfileController')->only([
    'index', 'update'
]);

Route::get('/home', 'HomeController@index')->name('home');

// CRUD Item
// Menambahkan resourceful route
Route::resource('item', 'ItemController');

// CRUD Category
// Menambahkan resourceful route
Route::resource('category', 'CategoryController');

//CRUD Cart
//Menambahkan cart
Route::get('/add-to-cart/{item}', 'CartController@add')->name('cart.add')->middleware('auth');
Route::get('/cart', 'CartController@index')->name('cart.index')->middleware('auth');
Route::get('/cart/destroy/{item_id}', 'CartController@destroy')->name('cart.destroy')->middleware('auth');
Route::get('/cart/update/{item_id}', 'CartController@update')->name('cart.update')->middleware('auth');
Route::get('/checkout', 'CartController@checkout')->name('cart.checkout')->middleware('auth');

Route::resource('cart_order', 'CartOrderController')->middleware('auth');

Route::post('/review', 'ReviewController@review');

resources/views/category copy/create.blade.php
@extends('layouts.master')

@section('title')
    Add Category
@endsection

@section('content')
    @error('name')
    <div class="alert alert-danger">
        {{ $message }}
    </div>
    @enderror

    <div class="col-14 ">
        
    
        <div class="card " style="display: flex; justify-content: center;">
            <div class="card-body" data-width="100%">
                <form action="/category" method="POST">
                    @csrf
                    <div class="form-group">
                        <label>Name</label>
                        <input type="text" class="form-control" name="name" id="name" placeholder="Enter Name">
                        
                        <button type="submit" class="btn btn-primary mt-3" style="border-radius=3px;">Add</button>
                    </div>
                
                    
                </form>
            </div>
        </div>
    </div>

   
@endsection

resources/views/category copy/edit.blade.php
@extends('layouts.master')

@section('title')
    Edit Category
@endsection

@section('content')
@error('name')
                            <div class="alert alert-danger">
                                {{ $message }}
                            </div>
                        @enderror
 <div class="col-14 ">
       
        <div class="card " style="display: flex; justify-content: center;">
            <div class="card-body" data-width="100%">
                <form action="/category/{{$category->id}}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('put')
                    <div class="form-group">
                        <label>Name</label>
                        <input type="text" class="form-control" value="{{$category->name}}" name="name" placeholder="Enter Name">
                        
                        <button type="submit" class="btn btn-primary mt-3" style="border-radius=3px;">Update</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
   
@endsection

resources/views/category copy/index.blade.php
@extends('layouts.master')

@section('title')
    Category List
@endsection

@section('content')
<h2 class="section-title">Category List</h2>
<p class="section-lead">
    Add, update, delete or view categories on this page.
</p>
<div class="row">
    <div class="col-12 col-sm-12">

        <div class="card" style="display: flex;">
            <div class="card" style="display: flex; margin-top: -10px">
                <div class="card-header">
                    @auth
                    <a href="{{route('category.create')}}" class="btn btn-primary" style="border-radius: 3px">
                        <i class="nav-icon fas fa-plus-circle"></i>
                        Add Category
                    </a>
                    @endauth
                </div>
            </div>
            <div class="card-body" data-width="100%">
                <table class="table">
                    <thead class="thead-light">
                      <tr>
                        <th scope="col">#</th>
                        <th scope="col">Name</th>
                        <th scope="col">Actions</th>
                      </tr>
                    </thead>
                    <tbody>
                        @forelse ($category as $key=>$value)
                            <tr>
                                <td>{{$key + 1}}</th>
                                <td>{{$value->name}}</td>
                                <td>
                                    <a href="/category/{{$value->id}}" class="btn btn-info">Show</a>
                                    <a href="/category/{{$value->id}}/edit" class="btn btn-warning">Edit</a>
                                    <form action="/category/{{$value->id}}" method="POST" style="display:inline;">
                                        @csrf
                                        @method('DELETE')
                                        <input type="submit" class="btn btn-danger my-1" value="Delete">
                                    </form>
                                </td>
                            </tr>
                        @empty
                            <h1>No Category</h1> 
                        @endforelse              
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>



@endsection 

resources/views/category copy/show.blade.php
@extends('layouts.master')

@section('title')
    Detail Category : {{$category->name}}
@endsection

@section('content')

<h1>{{$category->name}}</h1>

<!-- Menampilkan item berdasarkan category -->

<div class="row">
@forelse ($category->item as $temp)
<div class="col-lg-4">
    <div class="row justify-content-start">
        <div class="card mt-3 mx-3" style="width: 88%;">
            <img class="card-img-top" src="{{asset('images/'.$temp->thumbnail)}}" alt="Card image cap">
            <div class="card-body">
                <h5>{{$temp->name}}</h5>
                <h5>{{$temp->price}}</h5>
                <p class="card-text">{{ Str::limit($temp->specs, 125)}}</p>

                @auth
                        <form action="{{route('item.destroy', $temp->id)}}" method="POST">
                            @csrf
                            @method('delete')
                            <a href="{{route('item.show', $temp->id)}}" class="btn btn-info btn-sm">Detail</a>
                            <a href="{{route('item.edit', $temp->id)}}" class="btn btn-warning btn-sm">Edit</a>
                            <input type="submit" class="btn btn-danger btn-sm" value="Delete">
                            <a href="{{route('cart.add', $temp->id)}}" class="btn btn-success btn-sm">
                                <i class="nav-icon fas fa-cart-plus"></i>
                                Add to cart
                            </a>
                        </form>

                        @endauth

                    @guest
                        <a href="{{route('item.show', $temp->id)}}" class="btn btn-info btn-sm">Detail</a>
                        <a href="{{route('cart.add', $temp->id)}}" class="btn btn-success btn-sm">
                            <i class="nav-icon fas fa-cart-plus"></i>
                            Add to cart
                        </a>
                    @endguest
                    
            </div>
        </div>
    </div>
</div>
@empty
    <h1> Tidak ada item dengan category ini </h1>
@endforelse

</div>

@endsection