routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Auth::routes();

Route::resource('profile', 'ProfileController')->only([
    'index', 'update'
]);

Route::get('/home', 'HomeController@index')->name('home');

// CRUD Item
// Menambahkan resourceful route
Route::resource('item', 'ItemController');

// CRUD Category
// Menambahkan resourceful route
Route::resource('category', 'CategoryController');

//CRUD Cart
//Menambahkan cart
Route::get('/add-to-cart/{item}', 'CartController@add')->name('cart.add')->middleware('auth');
Route::get('/cart', 'CartController@index')->name('cart.index')->middleware('auth');
Route::get('/cart/destroy/{item_id}', 'CartController@destroy')->name('cart.destroy')->middleware('auth');
Route::get('/cart/update/{item_id}', 'CartController@update')->name('cart.update')->middleware('auth');
Route::get('/checkout', 'CartController@checkout')->name('cart.checkout')->middleware('auth');

Route::resource('cart_order', 'CartOrderController')->middleware('auth');

Route::post('/review', 'ReviewController@review');

resources/views/cart copy/checkout.blade.php
@extends('layouts.master')

@section('title')
    Checkout
@endsection

@section('content')
<form action="{{route('cart_order.store')}}" method="POST">
    @csrf
    <div class="form-group">
        <label>Name</label>
        <input type="text" class="form-control" name="name" id="name" value="{{$profile->user->name}}">
        @error('name')
            <div class="alert alert-danger">
                {{ $message }}
            </div>
        @enderror
    </div>
    <div class="form-group">
        <label for="items">Shipping Address</label>
        <input type="text" class="form-control" name="shipping_address" placeholder="Address">
        @error('address')
        <div class="alert alert-danger">
            {{ $message }}
        </div>
    @enderror
    </div>
    <div class="form-group">
        <label>Total Price: ¥ {{Cart::session(auth()->id())->getTotal()}}</label>
    </div>
    <div class="form-group">
        <label>Shipping Cost: ¥ {{$cart_order->shipping_cost}}</label>
    </div>
    <button type="submit" class="btn btn-success">Checkout</button>
</form>
@endsection 

resources/views/cart copy/index.blade.php
@extends('layouts.master')

@section('title')
    Your Cart
@endsection

@section('content')
<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Subtotal</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($cartItems as $temp)
        <tr>
            <td scope="row">{{ $temp->name }}</td>
            <td>{{ $temp->price }}</td>
            <td>
                <form action="{{route('cart.update', $temp->id)}}">
                    <input name="quantity" type="number" value="{{ $temp->quantity }}">
                    <input type="submit" value="save" class="btn btn-success btn-sm">
                </form>
            </td>
            <td>
                {{Cart::session(auth()->id())->get($temp->id)->getPriceSum()}}
            </td>
            <td>
               <a href="{{route('cart.destroy', $temp->id)}}" class="btn btn-danger btn-sm">Delete</a>
            </td>
        </tr>
        @endforeach
    </tbody>
</table>
<h3>Total Price: ¥ {{Cart::session(auth()->id())->getTotal()}}</h3>
<a href="{{route('cart.checkout')}}" class="btn btn-primary d-flex justify-content-center"> Proceed to Checkout </a>
@endsection 